export const InvestmentsImages: Record<"Commodity" | "Forex" | "Stocks" | "Crypto", Record<string, ImageData>> = {
  Crypto: {
    Bitcoin: require("../assets/Investment/Crypto/Bitcoin.png"),
    Ethereum: require("../assets/Investment/Crypto/Ethereum.png"),
    "Binance Coin": require("../assets/Investment/Crypto/Binance.png"),
    Solana: require("../assets/Investment/Crypto/Solana.png"),
    Ripple: require("../assets/Investment/Crypto/Ripple.png"),
    Cardano: require("../assets/Investment/Crypto/Cardano.png"),
    Avalanche: require("../assets/Investment/Crypto/Avalanche.png"),
    TRON: require("../assets/Investment/Crypto/Tron.png"),
    Dogecoin: require("../assets/Investment/Crypto/Dogecoin.png"),
    Chainlink: require("../assets/Investment/Crypto/Chainlink.png"),
    Polkadot: require("../assets/Investment/Crypto/Polkadot.png"),
    Polygon: require("../assets/Investment/Crypto/Matic.png"),
    Uniswap: require("../assets/Investment/Crypto/Uniswap.png"),
    Litecoin: require("../assets/Investment/Crypto/Litecoin.png"),
    Monero: require("../assets/Investment/Crypto/Monero.png"),
  },
  Stocks: {
    Bluetock: require("../assets/Investment/Stocks/Bluetock.png"),
    Ecrofoft: require("../assets/Investment/Stocks/Ecrofoft.png"),
    Emajon: require("../assets/Investment/Stocks/Emajon.png"),
    Fetfix: require("../assets/Investment/Stocks/Fetfix.png"),
    Loogel: require("../assets/Investment/Stocks/Loogel.png"),
    Sapple: require("../assets/Investment/Stocks/Sapple.png"),
    Sikee: require("../assets/Investment/Stocks/Sikee.png"),
    Tyluz: require("../assets/Investment/Stocks/Tyluz.png"),
    Zamtung: require("../assets/Investment/Stocks/Zamtung.png"),
    Zoosle: require("../assets/Investment/Stocks/Zoosle.png"),
  },
  Forex: {
    "Nepalese Rupee": require("../assets/Investment/Forex/Nepal.png"),
    Euro: require("../assets/Investment/Forex/Euro.png"),
    "Pound Sterling": require("../assets/Investment/Forex/UK.png"),
    "Indian Rupee": require("../assets/Investment/Forex/India.png"),
    "Russian Ruble": require("../assets/Investment/Forex/Russia.png"),
    "Canadian Dollar": require("../assets/Investment/Forex/Canada.png"),
    "Danish Krone": require("../assets/Investment/Forex/Denmark.png"),
    "New Zealand Dollar": require("../assets/Investment/Forex/NewZealand.png"),
    "Chinese Yuan": require("../assets/Investment/Forex/China.png"),
    "Australian Dollar": require("../assets/Investment/Forex/Australia.png"),
    "Mongolian Tugrik": require("../assets/Investment/Forex/Mongolia.png"),
    "Japanese Yen": require("../assets/Investment/Forex/Japan.png"),
    "Icelandic Króna": require("../assets/Investment/Forex/Iceland.png"),
    "Egyptian Pound": require("../assets/Investment/Forex/Egypt.png"),
    "Nigerian Naira": require("../assets/Investment/Forex/Nigeria.png"),
    "Kazakhstani Tenge": require("../assets/Investment/Forex/Kazakhstan.png"),
  },
  Commodity: {
    Gold: require("../assets/Investment/Commodity/bar.png"),
    Diamond: require("../assets/Investment/Commodity/diamond.png"),
    Silver: require("../assets/Investment/Commodity/bar.png"),
    Rice: require("../assets/Investment/Commodity/rice.png"),
    Oil: require("../assets/Investment/Commodity/oil.png"),
    Iron: require("../assets/Investment/Commodity/bar.png"),
    Steel: require("../assets/Investment/Commodity/steel.png"),
    Copper: require("../assets/Investment/Commodity/copper.png"),
    Gas: require("../assets/Investment/Commodity/gas.png"),
  },
};
